package cn.pacificimmi.common.models;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("crm_activity", "activity_id", Activity.class);
		arp.addMapping("crm_activity_sign", "sign_id", ActivitySign.class);
		arp.addMapping("console_dictionary", "dict_id", Dictionary.class);
		arp.addMapping("console_orgnization", "org_id", Orgnization.class);
		arp.addMapping("crm_business_cooperation", "id", BusinessCooperation.class);
		arp.addMapping("crm_business_negotiation", "id", BusinessNegotiation.class);
		arp.addMapping("crm_address_city", "CityId", AddressCity.class);
		arp.addMapping("crm_address_country", "CountryId", AddressCountry.class);
		arp.addMapping("crm_address_province", "ProvinceId", AddressProvince.class); 
		
		arp.addMapping("crm_custinfo", "custinfo_id", Custinfo.class);
		arp.addMapping("crm_custinfo_invoice", "custinfo_invoice_id", CustinfoInvoice.class);
		arp.addMapping("crm_custinfo_receive", "custinfo_receive_id", CustinfoReceive.class);
		arp.addMapping("crm_custinfo_security", "custinfo_security_id", CustinfoSecurity.class);
		arp.addMapping("crm_custinfo_steward", "id", CustinfoSteward.class);
		arp.addMapping("crm_custinfo_feedback", "custinfo_feedback_id", CustinfoFeedback.class);
		
		arp.addMapping("crm_distribution_main", "distribution_main_id", DistributionMain.class);
		arp.addMapping("crm_distribution_scale", "distribution_scale_id", DistributionScale.class);
		arp.addMapping("crm_distribution_set", "distribution_set_id", DistributionSet.class);
		arp.addMapping("crm_distribution_type", "distribution_type_id", DistributionType.class);
		
		arp.addMapping("crm_project", "project_id", Project.class);
		arp.addMapping("crm_project_apply_process", "project_apply_process_id", ProjectApplyProcess.class);
		arp.addMapping("crm_project_cost", "project_cost_id", ProjectCost.class);
		arp.addMapping("crm_project_expands", "project_expands_id", ProjectExpands.class);
		arp.addMapping("crm_project_material", "project_material_id", ProjectMaterial.class);
		arp.addMapping("crm_project_resource", "project_resource_id", ProjectResource.class);
		
		arp.addMapping("crm_steward_evaluate", "evaluate_id", StewardEvaluate.class);
		arp.addMapping("crm_steward_like", "like_id", StewardLike.class);
		arp.addMapping("crm_steward_sign", "sign_id", StewardSign.class);
		arp.addMapping("crm_steward_user", "steward_id", StewardUser.class);
		
		arp.addMapping("wx_card_access", "card_access_id", CardAccess.class);
		arp.addMapping("wx_card_customer", "card_customer_id", CardCustomer.class);
		arp.addMapping("wx_weixin_resource", "weixin_resource_id", WeixinResource.class);
		
		arp.addMapping("wx_estimate_question", "estimate_question_id", EstimateQuestion.class);
		arp.addMapping("wx_estimate_question_version", "version_id", EstimateQuestionVersion.class);
		arp.addMapping("wx_estimate_record", "estimate_record_id", EstimateRecord.class);
		arp.addMapping("wx_estimate_select", "estimate_select_id", EstimateSelect.class);
		arp.addMapping("wx_estimate_select_additional", "estimate_select_additional_id", EstimateSelectAdditional.class);
		arp.addMapping("wx_estimatet_detail_record", "estimate_detail_record_id", EstimatetDetailRecord.class);
		
		arp.addMapping("crm_country", "id", Country.class);
		arp.addMapping("console_user", "user_id", User.class);
		
		arp.addMapping("portal_channel", "channel_id", Channel.class);
		arp.addMapping("portal_invitation_code", "id", InvitationCode.class);
		arp.addMapping("portal_live", "live_id", Live.class);
		arp.addMapping("portal_live_application", "application_id", LiveApplication.class);
		arp.addMapping("portal_live_message", "message_id", LiveMessage.class);
		arp.addMapping("portal_live_like", "id", LiveLike.class);
		
		arp.addMapping("official_copyright", "copyright_id", Copyright.class);
		arp.addMapping("official_friendly_link", "friendly_link_id", FriendlyLink.class);
		arp.addMapping("official_nav_menu", "nav_menu_id", NavMenu.class);
		arp.addMapping("official_page_footers", "page_footers_id", PageFooters.class);
		arp.addMapping("official_page_headers", "page_headers_id", PageHeaders.class);
		arp.addMapping("official_custinfo_message", "custinfo_message_id", CustinfoMessage.class);
		
		arp.addMapping("crm_topics", "topic_id", Topics.class);
		arp.addMapping("crm_topic_setting", "setting_id", TopicSetting.class);
	}
}

