package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCrmSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmSection extends BaseCrmSection<CrmSection> {
	public static final CrmSection dao = new CrmSection();
}
