package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimateSelect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateSelect extends BaseEstimateSelect<EstimateSelect> {
	public static final EstimateSelect dao = new EstimateSelect();
}
