package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimatetDetailRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimatetDetailRecord extends BaseEstimatetDetailRecord<EstimatetDetailRecord> {
	public static final EstimatetDetailRecord dao = new EstimatetDetailRecord();
}
