package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEstimateRecord<M extends BaseEstimateRecord<M>> extends Model<M> implements IBean {

	public void setEstimateRecordId(java.lang.Integer estimateRecordId) {
		set("estimate_record_id", estimateRecordId);
	}

	public java.lang.Integer getEstimateRecordId() {
		return get("estimate_record_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setVersionId(java.lang.Integer versionId) {
		set("version_id", versionId);
	}

	public java.lang.Integer getVersionId() {
		return get("version_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
