package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStewardUser<M extends BaseStewardUser<M>> extends Model<M> implements IBean {

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}

	public java.lang.String getLoginName() {
		return get("login_name");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setEnglishName(java.lang.String englishName) {
		set("english_name", englishName);
	}

	public java.lang.String getEnglishName() {
		return get("english_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setComId(java.lang.String comId) {
		set("com_id", comId);
	}

	public java.lang.String getComId() {
		return get("com_id");
	}

	public void setDepId(java.lang.String depId) {
		set("dep_id", depId);
	}

	public java.lang.String getDepId() {
		return get("dep_id");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return get("gender");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("head_img", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("head_img");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setProvinceId(java.lang.String provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.String getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.String cityId) {
		set("city_id", cityId);
	}

	public java.lang.String getCityId() {
		return get("city_id");
	}

	public void setDistrict(java.lang.String district) {
		set("district", district);
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}

	public java.lang.String getWechat() {
		return get("wechat");
	}

	public void setJobTitle(java.lang.String jobTitle) {
		set("job_title", jobTitle);
	}

	public java.lang.String getJobTitle() {
		return get("job_title");
	}

	public void setReleaseMark(java.lang.String releaseMark) {
		set("release_mark", releaseMark);
	}

	public java.lang.String getReleaseMark() {
		return get("release_mark");
	}

	public void setStewardCode(java.lang.String stewardCode) {
		set("steward_code", stewardCode);
	}

	public java.lang.String getStewardCode() {
		return get("steward_code");
	}

	public void setStewardPcode(java.lang.String stewardPcode) {
		set("steward_pcode", stewardPcode);
	}

	public java.lang.String getStewardPcode() {
		return get("steward_pcode");
	}

	public void setEmployCount(java.lang.Integer employCount) {
		set("employ_count", employCount);
	}

	public java.lang.Integer getEmployCount() {
		return get("employ_count");
	}

	public void setCardStatus(java.lang.Integer cardStatus) {
		set("card_status", cardStatus);
	}

	public java.lang.Integer getCardStatus() {
		return get("card_status");
	}

	public void setLikeCount(java.lang.Integer likeCount) {
		set("like_count", likeCount);
	}

	public java.lang.Integer getLikeCount() {
		return get("like_count");
	}

}
